export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED';
export const CREATE_USER_TO_INITIAL = 'CREATE_USER_TO_INITIAL';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';


